### ISSUE TITLE
NeoShow() Error

### ISSUE THREAD

**Issue by HusseinShahin** [ghi-electronics/duelink-website#143]
The NeoPixel Scripts on this page use the NeoShow(pixels_number) function with one argument, meanwhile, the new API has 2 NeoShow(pin,pixels_number) which raise an error in the DUE console

**Comment by greg-norris** [comment]
What page are you referring to? 

This page shows 2 arguments
https://duelink.com/software/due-script/corelib/neopixel.html

**Comment by greg-norris** [comment]
Fixed in PR #150
