### ISSUE TITLE
i2cbytes api changed

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/duelink-website#84]
It was i2cbytes(address, writeNum, readNum).

After adding array, it becomes:

i2cbytes(address, arrayWrite, writeNum, arrayRead, readNum);

example:

dim a[1]
a[0] = 1
dim b[6]
i2cbytes(0x1c, a, 1, b, 6) // write 1 byte, read 6 bytes

**Comment by greg-norris** [comment]
added
